In [1]:
import numpy as np  # import auxiliary library, typical idiom
import pandas as pd  # import the Pandas library, typical idiom
from datetime import datetime
from datetime import date
from datetime import time
from datetime import datetime
from datetime import timedelta

from numba import jit

from sklearn.linear_model import LinearRegression  # for linear regression
from sklearn.cluster import KMeans  # for clustering
from sklearn.tree import DecisionTreeClassifier  # for decision tree mining
from sklearn.metrics import mean_absolute_error, confusion_matrix, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

In [2]:
file_export = 'export2012.csv'
data = pd.read_csv(file_export)

In [31]:
data_next_event = data.copy()

#A function for determining the true next event for each event
@jit(parallel = True)
def calculator_nb(case, event):
    res = np.empty(len(case), dtype=object)
    idx = 0
    for _ in case:
        if (idx+1 >= len(case)):
            break
       
        if (case[idx + 1] == case[idx]):
            res[idx] = event[idx + 1]

        idx+=1
    return res

data_next_event["next_task"] = calculator_nb(data_iterrated['case'].values, data_iterrated["event"].values)

C:\Users\mikok\AppData\Local\Temp\ipykernel_9352\454068311.py:4: NumbaWarning:
Compilation is falling back to object mode WITH looplifting enabled because Function "calculator_nb" failed type inference due to: Untyped global name 'object': Cannot determine Numba type of <class 'type'>

File "..\..\..\AppData\Local\Temp\ipykernel_9352\454068311.py", line 6:
<source missing, REPL/exec in use?>

  @jit(parallel = True)
C:\Users\mikok\AppData\Local\Temp\ipykernel_9352\454068311.py:4: NumbaWarning:
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "calculator_nb" failed type inference due to: Untyped global name 'object': Cannot determine Numba type of <class 'type'>

File "..\..\..\AppData\Local\Temp\ipykernel_9352\454068311.py", line 6:
<source missing, REPL/exec in use?>

  @jit(parallel = True)
C:\Users\mikok\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\object_mode_passes.py:151: NumbaWarning: Function "calculator_nb" was compiled in object mode without forceobj=True, but has lifted loops.

File "..\..\..\AppData\Local\Temp\ipykernel_9352\454068311.py", line 6:
<source missing, REPL/exec in use?>

  warnings.warn(errors.NumbaWarning(warn_msg,
C:\Users\mikok\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\object_mode_passes.py:161: NumbaDeprecationWarning:
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "..\..\..\AppData\Local\Temp\ipykernel_9352\454068311.py", line 6:
<source missing, REPL/exec in use?>

  warnings.warn(errors.NumbaDeprecationWarning(msg,
C:\Users\mikok\AppData\Local\Temp\ipykernel_9352\454068311.py:4: NumbaWarning:
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "calculator_nb" failed type inference due to: non-precise type array(pyobject, 1d, C)
During: typing of argument at C:\Users\mikok\AppData\Local\Temp\ipykernel_9352\454068311.py (8)

File "..\..\..\AppData\Local\Temp\ipykernel_9352\454068311.py", line 8:
<source missing, REPL/exec in use?>

  @jit(parallel = True)
C:\Users\mikok\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\object_mode_passes.py:151: NumbaWarning: Function "calculator_nb" was compiled in object mode without forceobj=True.

File "..\..\..\AppData\Local\Temp\ipykernel_9352\454068311.py", line 8:
<source missing, REPL/exec in use?>

  warnings.warn(errors.NumbaWarning(warn_msg,
C:\Users\mikok\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\object_mode_passes.py:161: NumbaDeprecationWarning:
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "..\..\..\AppData\Local\Temp\ipykernel_9352\454068311.py", line 8:
<source missing, REPL/exec in use?>

  warnings.warn(errors.NumbaDeprecationWarning(msg,

In [32]:
data_next_event

,case,event,startTime,completeTime,AMOUNT_REQ,REG_DATE,org:resource,next_task
0,173688,A_SUBMITTED,2011/10/01 00:38:44.546,2011/10/01 00:38:44.546,20000,2011/10/01 00:38:44.546,112,A_PARTLYSUBMITTED
1,173688,A_PARTLYSUBMITTED,2011/10/01 00:38:44.880,2011/10/01 00:38:44.880,20000,2011/10/01 00:38:44.546,112,A_PREACCEPTED
2,173688,A_PREACCEPTED,2011/10/01 00:39:37.906,2011/10/01 00:39:37.906,20000,2011/10/01 00:38:44.546,112,A_PREACCEPTED
3,173688,A_PREACCEPTED,2011/10/01 00:39:37.906,2011/10/01 00:39:37.906,20000,2011/10/01 00:38:44.546,112,W_Completeren aanvraag
4,173688,W_Completeren aanvraag,2011/10/01 11:36:46.437,2011/10/01 11:45:13.917,20000,2011/10/01 00:38:44.546,112,A_ACCEPTED
...,...,...,...,...,...,...,...,...
190822,214376,A_SUBMITTED,2012/02/29 23:51:16.799,2012/02/29 23:51:16.799,15000,2012/02/29 23:51:16.799,112,A_PARTLYSUBMITTED
190823,214376,A_PARTLYSUBMITTED,2012/02/29 23:51:17.423,2012/02/29 23:51:17.423,15000,2012/02/29 23:51:16.799,112,A_PARTLYSUBMITTED
190824,214376,A_PARTLYSUBMITTED,2012/02/29 23:51:17.423,2012/02/29 23:51:17.423,15000,2012/02/29 23:51:16.799,112,W_Afhandelen leads
190825,214376,W_Afhandelen leads,2012/03/01 09:26:46.736,2012/03/01 09:27:41.325,15000,2012/02/29 23:51:16.799,11169,A_DECLINED
190826,214376,A_DECLINED,2012/03/01 09:27:37.118,2012/03/01 09:27:37.118,15000,2012/02/29 23:51:16.799,11169,None

In [34]:
#Encodes each unique event as a number from 0 to 23
list_of_events = data_iterrated["event"].unique()
event_to_num = {}
i=0
for event in list_of_events:
    event_to_num[str(event)] = i
    i += 1
    
event_to_num['None'] = 23

In [35]:
#For each event, counts how many times another event occurs after it.
#Indexed based on list_of_events
count = {}
# initialise the count dictionary with zeros, otherwise it does not work
for event in list_of_events:
    #for k in range( len(event_to_num) ):
        count[str(event)] = [0 for i in range(len(list_of_events))]
 

for event in list_of_events:
    for k in range(len(list_of_events)):
        count[str(event)][k] = df_new[ (df_new['event'] == event) & (df_new['next_task'] == list_of_events[k]) ].count()['event']
        
        #if df_new[ df_new['event'] == df_new['next_task'] ]:
            
count

{'A_SUBMITTED': [0,
  13087,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'A_PARTLYSUBMITTED': [0,
  4806,
  4852,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  3429,
  0,
  4739,
  0,
  0,
  67],
 'A_PREACCEPTED': [0,
  0,
  7367,
  7367,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'W_Completeren aanvraag': [0,
  0,
  0,
  16486,
  5113,
  28,
  19,
  0,
  0,
  7,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1088,
  1120,
  0,
  0,
  0,
  3],
 'A_ACCEPTED': [0,
  0,
  0,
  74,
  0,
  2879,
  2089,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  25,
  46,
  0,
  0,
  0,
  0],
 'O_SELECTED': [0,
  0,
  0,
  0,
  0,
  1,
  2907,
  3149,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  974,
  0,
  0,
  0,
  0,
  0,
  0],
 'A_FINALIZED': [0,
  0,
  0,
  0,
  0,
  2108,
  0,
  2907,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'O_CREATED': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  7030,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'O_SENT': [0,
  0,
  0,
  3,
  0,
  0,
  0,
  0,
  7031,
  6621,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  396,
  0],
 'W_Nabellen offertes': [0,
  0,
  0,
  4,
  0,
  768,
  0,
  0,
  0,
  16280,
  3254,
  1,
  0,
  0,
  0,
  0,
  1554,
  27,
  788,
  0,
  21,
  0,
  0],
 'O_SENT_BACK': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  3455,
  3407,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0],
 'W_Valideren aanvraag': [0,
  0,
  0,
  0,
  0,
  107,
  0,
  0,
  0,
  0,
  0,
  4943,
  228,
  489,
  1136,
  198,
  111,
  320,
  13,
  0,
  348,
  1983,
  33],
 'A_REGISTERED': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  581,
  332,
  670,
  0,
  0,
  0,
  0,
  0,
  1,
  0],
 'A_APPROVED': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  682,
  0,
  474,
  789,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'O_ACCEPTED': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  771,
  654,
  2,
  566,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'A_ACTIVATED': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  546,
  478,
  192,
  5,
  0,
  0,
  0,
  0,
  0,
  1,
  0],
 'O_CANCELLED': [0,
  0,
  0,
  0,
  0,
  1041,
  0,
  974,
  0,
  33,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  767,
  0,
  0,
  0,
  0],
 'A_DECLINED': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  383,
  0,
  0],
 'A_CANCELLED': [0,
  0,
  0,
  34,
  0,
  0,
  0,
  0,
  0,
  34,
  0,
  1,
  0,
  0,
  0,
  0,
  864,
  0,
  0,
  0,
  0,
  0,
  0],
 'W_Afhandelen leads': [0,
  0,
  2515,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2234,
  1,
  1150,
  0,
  0,
  21],
 'O_DECLINED': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  419,
  0,
  0,
  0,
  0,
  0],
 'W_Nabellen incomplete dossiers': [0,
  0,
  0,
  0,
  0,
  99,
  0,
  0,
  0,
  0,
  200,
  1532,
  19,
  44,
  109,
  23,
  151,
  36,
  72,
  0,
  50,
  10562,
  0],
 'W_Beoordelen fraude': [0,
  0,
  0,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  33,
  0,
  0,
  0,
  0,
  0,
  57,
  0,
  32,
  0,
  0,
  213]}

In [13]:
#The main part of the naive predictor
#Takes the above dictionary and finds the most frequenly occuring consecutive
#event after each event
count2 = count
index = {}
for event in list_of_events:
    max = 0
    for k in range( len(list_of_events)-1 ):
        if count2[event][k] > max:
            max = count2[event][k]
            #print(max)
            index2 = k;
    index[event] = index2
index

{'A_SUBMITTED': 1,
 'A_PARTLYSUBMITTED': 2,
 'A_PREACCEPTED': 2,
 'W_Completeren aanvraag': 3,
 'A_ACCEPTED': 5,
 'O_SELECTED': 7,
 'A_FINALIZED': 7,
 'O_CREATED': 8,
 'O_SENT': 8,
 'W_Nabellen offertes': 9,
 'O_SENT_BACK': 10,
 'W_Valideren aanvraag': 11,
 'A_REGISTERED': 15,
 'A_APPROVED': 15,
 'O_ACCEPTED': 12,
 'A_ACTIVATED': 12,
 'O_CANCELLED': 5,
 'A_DECLINED': 20,
 'A_CANCELLED': 16,
 'W_Afhandelen leads': 2,
 'O_DECLINED': 17,
 'W_Nabellen incomplete dossiers': 21,
 'W_Beoordelen fraude': 17}

In [14]:
#Turns the above into an event to event dictionary
prediction = {}
for event in list_of_events:
    prediction[event] = list_of_events[index[event]]
    
prediction

{'A_SUBMITTED': 'A_PARTLYSUBMITTED',
 'A_PARTLYSUBMITTED': 'A_PREACCEPTED',
 'A_PREACCEPTED': 'A_PREACCEPTED',
 'W_Completeren aanvraag': 'W_Completeren aanvraag',
 'A_ACCEPTED': 'O_SELECTED',
 'O_SELECTED': 'O_CREATED',
 'A_FINALIZED': 'O_CREATED',
 'O_CREATED': 'O_SENT',
 'O_SENT': 'O_SENT',
 'W_Nabellen offertes': 'W_Nabellen offertes',
 'O_SENT_BACK': 'O_SENT_BACK',
 'W_Valideren aanvraag': 'W_Valideren aanvraag',
 'A_REGISTERED': 'A_ACTIVATED',
 'A_APPROVED': 'A_ACTIVATED',
 'O_ACCEPTED': 'A_REGISTERED',
 'A_ACTIVATED': 'A_REGISTERED',
 'O_CANCELLED': 'O_SELECTED',
 'A_DECLINED': 'O_DECLINED',
 'A_CANCELLED': 'O_CANCELLED',
 'W_Afhandelen leads': 'A_PREACCEPTED',
 'O_DECLINED': 'A_DECLINED',
 'W_Nabellen incomplete dossiers': 'W_Nabellen incomplete dossiers',
 'W_Beoordelen fraude': 'A_DECLINED'}

In [36]:
#Adds predicted event column
df_predicted_event = df_new.copy()
df_predicted_event["predicted_event"] = ["" for i in df_new2["event"]]
df_predicted_event['predicted_event'] = df_new2["event"].map(prediction)
df_predicted_event.head(50)

,case,event,startTime,completeTime,AMOUNT_REQ,REG_DATE,org:resource,next_task,predicted_event
0,173688,A_SUBMITTED,2011/10/01 00:38:44.546,2011/10/01 00:38:44.546,20000,2011/10/01 00:38:44.546,112,A_PARTLYSUBMITTED,A_PARTLYSUBMITTED
1,173688,A_PARTLYSUBMITTED,2011/10/01 00:38:44.880,2011/10/01 00:38:44.880,20000,2011/10/01 00:38:44.546,112,A_PREACCEPTED,A_PREACCEPTED
2,173688,A_PREACCEPTED,2011/10/01 00:39:37.906,2011/10/01 00:39:37.906,20000,2011/10/01 00:38:44.546,112,A_PREACCEPTED,A_PREACCEPTED
3,173688,A_PREACCEPTED,2011/10/01 00:39:37.906,2011/10/01 00:39:37.906,20000,2011/10/01 00:38:44.546,112,W_Completeren aanvraag,A_PREACCEPTED
4,173688,W_Completeren aanvraag,2011/10/01 11:36:46.437,2011/10/01 11:45:13.917,20000,2011/10/01 00:38:44.546,112,A_ACCEPTED,W_Completeren aanvraag
5,173688,A_ACCEPTED,2011/10/01 11:42:43.308,2011/10/01 11:42:43.308,20000,2011/10/01 00:38:44.546,10862,O_SELECTED,O_SELECTED
6,173688,O_SELECTED,2011/10/01 11:45:09.243,2011/10/01 11:45:09.243,20000,2011/10/01 00:38:44.546,10862,A_FINALIZED,O_CREATED
7,173688,A_FINALIZED,2011/10/01 11:45:09.243,2011/10/01 11:45:09.243,20000,2011/10/01 00:38:44.546,10862,O_CREATED,O_CREATED
8,173688,O_CREATED,2011/10/01 11:45:11.197,2011/10/01 11:45:11.197,20000,2011/10/01 00:38:44.546,10862,O_SENT,O_SENT
9,173688,O_SENT,2011/10/01 11:45:11.380,2011/10/01 11:45:11.380,20000,2011/10/01 00:38:44.546,10862,O_SENT,O_SENT
10,173688,O_SENT,2011/10/01 11:45:11.380,2011/10/01 11:45:11.380,20000,2011/10/01 00:38:44.546,10862,W_Nabellen offertes,O_SENT
11,173688,W_Nabellen offertes,2011/10/01 12:15:41.290,2011/10/01 12:17:08.924,20000,2011/10/01 00:38:44.546,10862,W_Nabellen offertes,W_Nabellen offertes
12,173688,W_Nabellen offertes,2011/10/08 16:26:57.720,2011/10/08 16:32:00.886,20000,2011/10/01 00:38:44.546,10913,W_Nabellen offertes,W_Nabellen offertes
13,173688,W_Nabellen offertes,2011/10/10 11:32:22.495,2011/10/10 11:33:05.791,20000,2011/10/01 00:38:44.546,11049,O_SENT_BACK,W_Nabellen offertes
14,173688,O_SENT_BACK,2011/10/10 11:33:03.668,2011/10/10 11:33:03.668,20000,2011/10/01 00:38:44.546,11049,O_SENT_BACK,O_SENT_BACK
15,173688,O_SENT_BACK,2011/10/10 11:33:03.668,2011/10/10 11:33:03.668,20000,2011/10/01 00:38:44.546,11049,W_Valideren aanvraag,O_SENT_BACK
16,173688,W_Valideren aanvraag,2011/10/13 10:05:26.925,2011/10/13 10:37:37.026,20000,2011/10/01 00:38:44.546,10629,A_REGISTERED,W_Valideren aanvraag
17,173688,A_REGISTERED,2011/10/13 10:37:29.226,2011/10/13 10:37:29.226,20000,2011/10/01 00:38:44.546,10629,A_APPROVED,A_ACTIVATED
18,173688,A_APPROVED,2011/10/13 10:37:29.226,2011/10/13 10:37:29.226,20000,2011/10/01 00:38:44.546,10629,O_ACCEPTED,A_ACTIVATED
19,173688,O_ACCEPTED,2011/10/13 10:37:29.226,2011/10/13 10:37:29.226,20000,2011/10/01 00:38:44.546,10629,A_ACTIVATED,A_REGISTERED
20,173688,A_ACTIVATED,2011/10/13 10:37:29.226,2011/10/13 10:37:29.226,20000,2011/10/01 00:38:44.546,10629,None,A_REGISTERED
21,173691,A_SUBMITTED,2011/10/01 08:08:58.256,2011/10/01 08:08:58.256,5000,2011/10/01 08:08:58.256,112,A_PARTLYSUBMITTED,A_PARTLYSUBMITTED
22,173691,A_PARTLYSUBMITTED,2011/10/01 08:09:02.195,2011/10/01 08:09:02.195,5000,2011/10/01 08:08:58.256,112,A_PREACCEPTED,A_PREACCEPTED
23,173691,A_PREACCEPTED,2011/10/01 08:09:56.648,2011/10/01 08:09:56.648,5000,2011/10/01 08:08:58.256,112,A_PREACCEPTED,A_PREACCEPTED
24,173691,A_PREACCEPTED,2011/10/01 08:09:56.648,2011/10/01 08:09:56.648,5000,2011/10/01 08:08:58.256,112,W_Completeren aanvraag,A_PREACCEPTED
25,173691,W_Completeren aanvraag,2011/10/01 11:37:32.393,2011/10/01 11:43:13.178,5000,2011/10/01 08:08:58.256,112,W_Completeren aanvraag,W_Completeren aanvraag
26,173691,W_Completeren aanvraag,2011/10/01 14:27:57.775,2011/10/01 14:35:48.791,5000,2011/10/01 08:08:58.256,112,A_ACCEPTED,W_Completeren aanvraag
27,173691,A_ACCEPTED,2011/10/01 14:33:54.614,2011/10/01 14:33:54.614,5000,2011/10/01 08:08:58.256,10862,A_FINALIZED,O_SELECTED
28,173691,A_FINALIZED,2011/10/01 14:35:46.016,2011/10/01 14:35:46.016,5000,2011/10/01 08:08:58.256,10862,O_SELECTED,O_CREATED
29,173691,O_SELECTED,2011/10/01 14:35:46.016,2011/10/01 14:35:46.016,5000,2011/10/01 08:08:58.256,10862,O_CREATED,O_CREATED
30,173691,O_CREATED,2011/10/01 14:35:47.488,2011/10/01 14:35:47.488,5000,2011/10/01 08:08:58.256,10862,O_SENT,O_SENT
31,173691,O_SENT,2011/10/01 14:35:47.583,2011/10/01 14:35:47.583,5000,2011/10/01 08:08:58.256,10862,O_SENT,O_SENT
32,173691,O_SENT,2011/10/01 14:35:47.583,2011/10/01 14:35:47.583,5000,2011/10/01 08:08:58.256,10862,W_Nabellen offertes,O_SENT
33,173691,W_Nabellen offertes,2011/10/01 14:36:13.443,2011/10/01 14:36:25.794,5000,2011/10/01 08:08:58.256,10862,W_Nabellen offertes,W_Nabellen offertes
34,173691,W_Nabellen offertes,2011/10/03 16:54:43.257,2011/10/03 16:56:21.195,5000,2011/10/01 08:08:58.256,10862,O_SELECTED,W_Nabellen offertes
35,173691,O_SELECTED,2011/10/03 16:56:17.731,2011/10/03 16:56:17.731,5000,2011/10/01 08:08:58.256,11120,O_CANCELLED,O_CREATED
36,173691,O_CANCELLED,2011/10/03 16:56:17.731,2011/10/03 16:56:17.731,5000,2011/10/01 08:08:58.256,11120,O_CREATED,O_SELECTED
37,173691,O_CREATED,2011/10/03 16:56:19.613,2011/10/03 16:56:19.613,5000,2011/10/01 08:08:58.256,11120,O_SENT,O_SENT
38,173691,O_SENT,2011/10/03 16:56:19.645,2011/10/03 16:56:19.645,5000,2011/10/01 08:08:58.256,11120,O_SENT,O_SENT
39,173691,O_SENT,2011/10/03 16:56:19.645,2011/10/03 16:56:19.645,5000,2011/10/01 08:08:58.256,11120,W_Nabellen offertes,O_SENT
40,173691,W_Nabellen offertes,2011/10/03 16:56:34.792,2011/10/03 16:57:16.563,5000,2011/10/01 08:08:58.256,11120,W_Nabellen offertes,W_Nabellen offertes
41,173691,W_Nabellen offertes,2011/10/10 10:13:44.827,2011/10/10 10:14:45.514,5000,2011/10/01 08:08:58.256,11049,O_SENT_BACK,W_Nabellen offertes
42,173691,O_SENT_BACK,2011/10/10 10:14:43.775,2011/10/10 10:14:43.775,5000,2011/10/01 08:08:58.256,11049,O_SENT_BACK,O_SENT_BACK
43,173691,O_SENT_BACK,2011/10/10 10:14:43.775,2011/10/10 10:14:43.775,5000,2011/10/01 08:08:58.256,11049,W_Valideren aanvraag,O_SENT_BACK
44,173691,W_Valideren aanvraag,2011/10/10 11:12:36.612,2011/10/10 11:30:54.893,5000,2011/10/01 08:08:58.256,10809,W_Valideren aanvraag,W_Valideren aanvraag
45,173691,W_Valideren aanvraag,2011/10/10 14:11:42.124,2011/10/10 14:14:13.394,5000,2011/10/01 08:08:58.256,10809,W_Valideren aanvraag,W_Valideren aanvraag
46,173691,W_Valideren aanvraag,2011/10/10 14:14:52.842,2011/10/10 14:17:34.633,5000,2011/10/01 08:08:58.256,10809,O_ACCEPTED,W_Valideren aanvraag
47,173691,O_ACCEPTED,2011/10/10 14:17:26.306,2011/10/10 14:17:26.306,5000,2011/10/01 08:08:58.256,10809,A_APPROVED,A_REGISTERED
48,173691,A_APPROVED,2011/10/10 14:17:26.307,2011/10/10 14:17:26.307,5000,2011/10/01 08:08:58.256,10809,A_REGISTERED,A_ACTIVATED
49,173691,A_REGISTERED,2011/10/10 14:17:26.307,2011/10/10 14:17:26.307,5000,2011/10/01 08:08:58.256,10809,A_ACTIVATED,A_ACTIVATED

In [57]:
df_predicted_time = df_predicted_event.copy()
df_predicted_time["duration"] = pd.to_datetime(df_predicted_time["completeTime"]) - pd.to_datetime(result_data_str["startTime"])

#Sums up count for each event and the time each event takes
events_count = df_predicted_time.groupby("event")['duration'].agg('count')
event_duration_sum = df_predicted_time.groupby("event")['duration'].agg('sum')

#Computes average duration per event
duration_per_event = event_duration_sum / events_count

#Makes array with average duration per row
@jit(parallel = True)
def make_prediction(event, dict):
    res = np.empty(len(event), dtype=object)
    for idx,_ in enumerate(event):
        res[idx] = dict[event[idx]]
        
    return res

#Adds said array as a column
df_predicted_time["predicted_duration"] = make_prediction(df_predicted_time['event'].values, duration_per_event)

C:\Users\mikok\AppData\Local\Temp\ipykernel_9352\3461509183.py:12: NumbaWarning:
Compilation is falling back to object mode WITH looplifting enabled because Function "make_prediction" failed type inference due to: Untyped global name 'object': Cannot determine Numba type of <class 'type'>

File "..\..\..\AppData\Local\Temp\ipykernel_9352\3461509183.py", line 14:
<source missing, REPL/exec in use?>

  @jit(parallel = True)
C:\Users\mikok\AppData\Local\Temp\ipykernel_9352\3461509183.py:12: NumbaWarning:
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "make_prediction" failed type inference due to: Untyped global name 'object': Cannot determine Numba type of <class 'type'>

File "..\..\..\AppData\Local\Temp\ipykernel_9352\3461509183.py", line 14:
<source missing, REPL/exec in use?>

  @jit(parallel = True)
C:\Users\mikok\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\object_mode_passes.py:151: NumbaWarning: Function "make_prediction" was compiled in object mode without forceobj=True, but has lifted loops.

File "..\..\..\AppData\Local\Temp\ipykernel_9352\3461509183.py", line 14:
<source missing, REPL/exec in use?>

  warnings.warn(errors.NumbaWarning(warn_msg,
C:\Users\mikok\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\object_mode_passes.py:161: NumbaDeprecationWarning:
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "..\..\..\AppData\Local\Temp\ipykernel_9352\3461509183.py", line 14:
<source missing, REPL/exec in use?>

  warnings.warn(errors.NumbaDeprecationWarning(msg,
C:\Users\mikok\AppData\Local\Temp\ipykernel_9352\3461509183.py:12: NumbaWarning:
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "make_prediction" failed type inference due to: non-precise type pyobject
During: typing of argument at C:\Users\mikok\AppData\Local\Temp\ipykernel_9352\3461509183.py (15)

File "..\..\..\AppData\Local\Temp\ipykernel_9352\3461509183.py", line 15:
<source missing, REPL/exec in use?>

  @jit(parallel = True)
C:\Users\mikok\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\object_mode_passes.py:151: NumbaWarning: Function "make_prediction" was compiled in object mode without forceobj=True.

File "..\..\..\AppData\Local\Temp\ipykernel_9352\3461509183.py", line 15:
<source missing, REPL/exec in use?>

  warnings.warn(errors.NumbaWarning(warn_msg,
C:\Users\mikok\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\object_mode_passes.py:161: NumbaDeprecationWarning:
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "..\..\..\AppData\Local\Temp\ipykernel_9352\3461509183.py", line 15:
<source missing, REPL/exec in use?>

  warnings.warn(errors.NumbaDeprecationWarning(msg,

In [62]:
#Final cleanup
df_predicted_time = df_predicted_time.drop(['duration'], axis=1)
df_predicted_time = df_predicted_time.drop(['next_task'], axis=1)

In [63]:
#Adding predicted start time of next event
df_predicted_time['predicted_time'] = df_predicted_time["predicted_duration"] + pd.to_datetime(df_predicted_time["startTime"])

,case,event,startTime,completeTime,AMOUNT_REQ,REG_DATE,org:resource,predicted_event,predicted_duration,predicted_time
0,173688,A_SUBMITTED,2011/10/01 00:38:44.546,2011/10/01 00:38:44.546,20000,2011/10/01 00:38:44.546,112,A_PARTLYSUBMITTED,0 days 00:00:00,2011-10-01 00:38:44.546000000
1,173688,A_PARTLYSUBMITTED,2011/10/01 00:38:44.880,2011/10/01 00:38:44.880,20000,2011/10/01 00:38:44.546,112,A_PREACCEPTED,0 days 00:00:00,2011-10-01 00:38:44.880000000
2,173688,A_PREACCEPTED,2011/10/01 00:39:37.906,2011/10/01 00:39:37.906,20000,2011/10/01 00:38:44.546,112,A_PREACCEPTED,0 days 00:00:00,2011-10-01 00:39:37.906000000
3,173688,A_PREACCEPTED,2011/10/01 00:39:37.906,2011/10/01 00:39:37.906,20000,2011/10/01 00:38:44.546,112,A_PREACCEPTED,0 days 00:00:00,2011-10-01 00:39:37.906000000
4,173688,W_Completeren aanvraag,2011/10/01 11:36:46.437,2011/10/01 11:45:13.917,20000,2011/10/01 00:38:44.546,112,W_Completeren aanvraag,0 days 00:10:00.791783229,2011-10-01 11:46:47.228783229
5,173688,A_ACCEPTED,2011/10/01 11:42:43.308,2011/10/01 11:42:43.308,20000,2011/10/01 00:38:44.546,10862,O_SELECTED,0 days 00:00:00,2011-10-01 11:42:43.308000000
6,173688,O_SELECTED,2011/10/01 11:45:09.243,2011/10/01 11:45:09.243,20000,2011/10/01 00:38:44.546,10862,O_CREATED,0 days 00:00:00,2011-10-01 11:45:09.243000000
7,173688,A_FINALIZED,2011/10/01 11:45:09.243,2011/10/01 11:45:09.243,20000,2011/10/01 00:38:44.546,10862,O_CREATED,0 days 00:00:00,2011-10-01 11:45:09.243000000
8,173688,O_CREATED,2011/10/01 11:45:11.197,2011/10/01 11:45:11.197,20000,2011/10/01 00:38:44.546,10862,O_SENT,0 days 00:00:00,2011-10-01 11:45:11.197000000
9,173688,O_SENT,2011/10/01 11:45:11.380,2011/10/01 11:45:11.380,20000,2011/10/01 00:38:44.546,10862,O_SENT,0 days 00:00:00,2011-10-01 11:45:11.380000000
10,173688,O_SENT,2011/10/01 11:45:11.380,2011/10/01 11:45:11.380,20000,2011/10/01 00:38:44.546,10862,O_SENT,0 days 00:00:00,2011-10-01 11:45:11.380000000
11,173688,W_Nabellen offertes,2011/10/01 12:15:41.290,2011/10/01 12:17:08.924,20000,2011/10/01 00:38:44.546,10862,W_Nabellen offertes,0 days 00:09:04.889493362,2011-10-01 12:24:46.179493362
12,173688,W_Nabellen offertes,2011/10/08 16:26:57.720,2011/10/08 16:32:00.886,20000,2011/10/01 00:38:44.546,10913,W_Nabellen offertes,0 days 00:09:04.889493362,2011-10-08 16:36:02.609493362
13,173688,W_Nabellen offertes,2011/10/10 11:32:22.495,2011/10/10 11:33:05.791,20000,2011/10/01 00:38:44.546,11049,W_Nabellen offertes,0 days 00:09:04.889493362,2011-10-10 11:41:27.384493362
14,173688,O_SENT_BACK,2011/10/10 11:33:03.668,2011/10/10 11:33:03.668,20000,2011/10/01 00:38:44.546,11049,O_SENT_BACK,0 days 00:00:00,2011-10-10 11:33:03.668000000
15,173688,O_SENT_BACK,2011/10/10 11:33:03.668,2011/10/10 11:33:03.668,20000,2011/10/01 00:38:44.546,11049,O_SENT_BACK,0 days 00:00:00,2011-10-10 11:33:03.668000000
16,173688,W_Valideren aanvraag,2011/10/13 10:05:26.925,2011/10/13 10:37:37.026,20000,2011/10/01 00:38:44.546,10629,W_Valideren aanvraag,0 days 00:21:04.323053936,2011-10-13 10:26:31.248053936
17,173688,A_REGISTERED,2011/10/13 10:37:29.226,2011/10/13 10:37:29.226,20000,2011/10/01 00:38:44.546,10629,A_ACTIVATED,0 days 00:00:00,2011-10-13 10:37:29.226000000
18,173688,A_APPROVED,2011/10/13 10:37:29.226,2011/10/13 10:37:29.226,20000,2011/10/01 00:38:44.546,10629,A_ACTIVATED,0 days 00:00:00,2011-10-13 10:37:29.226000000
19,173688,O_ACCEPTED,2011/10/13 10:37:29.226,2011/10/13 10:37:29.226,20000,2011/10/01 00:38:44.546,10629,A_REGISTERED,0 days 00:00:00,2011-10-13 10:37:29.226000000
20,173688,A_ACTIVATED,2011/10/13 10:37:29.226,2011/10/13 10:37:29.226,20000,2011/10/01 00:38:44.546,10629,A_REGISTERED,0 days 00:00:00,2011-10-13 10:37:29.226000000
21,173691,A_SUBMITTED,2011/10/01 08:08:58.256,2011/10/01 08:08:58.256,5000,2011/10/01 08:08:58.256,112,A_PARTLYSUBMITTED,0 days 00:00:00,2011-10-01 08:08:58.256000000
22,173691,A_PARTLYSUBMITTED,2011/10/01 08:09:02.195,2011/10/01 08:09:02.195,5000,2011/10/01 08:08:58.256,112,A_PREACCEPTED,0 days 00:00:00,2011-10-01 08:09:02.195000000
23,173691,A_PREACCEPTED,2011/10/01 08:09:56.648,2011/10/01 08:09:56.648,5000,2011/10/01 08:08:58.256,112,A_PREACCEPTED,0 days 00:00:00,2011-10-01 08:09:56.648000000
24,173691,A_PREACCEPTED,2011/10/01 08:09:56.648,2011/10/01 08:09:56.648,5000,2011/10/01 08:08:58.256,112,A_PREACCEPTED,0 days 00:00:00,2011-10-01 08:09:56.648000000
25,173691,W_Completeren aanvraag,2011/10/01 11:37:32.393,2011/10/01 11:43:13.178,5000,2011/10/01 08:08:58.256,112,W_Completeren aanvraag,0 days 00:10:00.791783229,2011-10-01 11:47:33.184783229
26,173691,W_Completeren aanvraag,2011/10/01 14:27:57.775,2011/10/01 14:35:48.791,5000,2011/10/01 08:08:58.256,112,W_Completeren aanvraag,0 days 00:10:00.791783229,2011-10-01 14:37:58.566783229
27,173691,A_ACCEPTED,2011/10/01 14:33:54.614,2011/10/01 14:33:54.614,5000,2011/10/01 08:08:58.256,10862,O_SELECTED,0 days 00:00:00,2011-10-01 14:33:54.614000000
28,173691,A_FINALIZED,2011/10/01 14:35:46.016,2011/10/01 14:35:46.016,5000,2011/10/01 08:08:58.256,10862,O_CREATED,0 days 00:00:00,2011-10-01 14:35:46.016000000
29,173691,O_SELECTED,2011/10/01 14:35:46.016,2011/10/01 14:35:46.016,5000,2011/10/01 08:08:58.256,10862,O_CREATED,0 days 00:00:00,2011-10-01 14:35:46.016000000

In [42]:
df_predicted_time.to_csv('sprint1.csv')